# -*- coding: utf-8 -*-
from odoo import api, fields, models, _ , Command
from odoo.exceptions import UserError
from datetime import timedelta

class PosOrder(models.Model):
    _inherit = 'pos.order'

    mrp_production_count = fields.Integer(
        "Count of MO generated",
        compute='_compute_mrp_production_ids',
        )
    
    mrp_production_ids = fields.Many2many(
        'mrp.production',
        string='Manufacturing orders associated with this pos order line.',
        compute="_compute_mrp_production_ids"
        )
    
    
    def _compute_mrp_production_ids(self):
        for rec in self:
            rec.mrp_production_ids = [Command.link(mrp.id) for mrp in rec.lines.mrp_production_ids]
            rec.mrp_production_count = len(rec.mrp_production_ids)

    
    def action_view_mrp_production(self):
        self.ensure_one()
        action = {
            'res_model': 'mrp.production',
            'type': 'ir.actions.act_window',
        }
        if len(self.mrp_production_ids) == 1:
            action.update({
                'view_mode': 'form',
                'res_id': self.mrp_production_ids.id,
            })
        else:
            action.update({
                'name': _("Manufacturing Orders Generated by %s", self.name),
                'domain': [('id', 'in', self.mrp_production_ids.ids)],
                'view_mode': 'list,form',
            })
        return action
    
    # @api.model
    # def _process_order(self, order, existing_order):
    #     super()._process_order(order, existing_order)
    
    def _create_order_picking(self):
        self.ensure_one()
        
        lines_to_manufacture = self.lines.filtered(
            lambda line: line.product_id.can_create_pos_mrp 
        )
        
        if lines_to_manufacture:
            self._create_mrp_from_pos(lines_to_manufacture)
            
            normal_lines = self.lines - lines_to_manufacture
            if normal_lines:
                self._process_normal_lines(normal_lines)
        else:
            super()._create_order_picking()

    def _process_normal_lines(self, normal_lines):
        """Procesar líneas normales con la misma lógica que el método original"""
        self.ensure_one()
        
        if self.shipping_date:
            self.sudo(normal_lines)._launch_stock_rule_from_pos_order_lines()
        else:
            if self._should_create_picking_real_time():
                picking_type = self.config_id.picking_type_id
                if self.partner_id.property_stock_customer:
                    destination_id = self.partner_id.property_stock_customer.id
                elif not picking_type or not picking_type.default_location_dest_id:
                    destination_id = self.env['stock.warehouse']._get_partner_locations()[0].id
                else:
                    destination_id = picking_type.default_location_dest_id.id

                pickings = self.env['stock.picking']._create_picking_from_pos_order_lines(
                    destination_id, normal_lines, picking_type, self.partner_id
                )
                pickings.write({
                    'pos_session_id': self.session_id.id, 
                    'pos_order_id': self.id, 
                    'origin': self.name
                })

    def _create_mrp_from_pos(self, lines):
        """Crear órdenes de fabricación y pickings en borrador desde PDV"""
        self.ensure_one()
        mrp_productions = self.env['mrp.production']
        group = self.env["procurement.group"].create({
            'name': self.name,
            'partner_id': self.partner_id.id,
            'move_type': 'one',
        }) 
        for line in lines:
            mrp_productions += self._create_mrp_production(line,group)
        self._create_draft_picking_for_productions(mrp_productions,group)
    
    def _create_mrp_production(self, line,group):
        product = line.product_id
        bom = self.env['mrp.bom']._bom_find(product)[product]
        if not bom:
            raise UserError(_('No lista de materiales para %s') % product.name)
        
             

        mrp_order = self.env['mrp.production'].create({
            'product_id': product.id,
            'product_qty': abs(line.qty),
            'product_uom_id': product.uom_id.id,
            'bom_id': bom.id,
            'origin': self.name,
            'pos_order_line_id': line.id,
            'state': 'confirmed',
            'procurement_group_id': group.id,   
        })
        mrp_order.move_raw_ids =  [ Command.create(m) for m in mrp_order._get_moves_raw_values()]
        mrp_order.move_finished_ids =  [ Command.create(m) for m in mrp_order._get_moves_finished_values()]
        
        return mrp_order
      
    def _create_draft_picking_for_productions(self, mrp_productions,group):
        self.ensure_one()
        picking_type = self.config_id.picking_type_id
        location_id = picking_type.default_location_src_id
        location_dest_id = (
            self.partner_id.property_stock_customer
            or picking_type.default_location_dest_id
        )

        picking = self.env['stock.picking'].create({
            'picking_type_id': picking_type.id,
            'location_id': location_id.id,            
            'location_dest_id': location_dest_id.id,
            'partner_id': self.partner_id.id,
            'origin': self.name,
            'pos_session_id': self.session_id.id,
            'pos_order_id': self.id,
            'group_id': group.id,
            'move_type': 'one',
            'state': 'draft', 
        })
        for mrp_production in mrp_productions:
            move_sale = self.env['stock.move'].create({
                'name': mrp_production.product_id.display_name,
                'product_id': mrp_production.product_id.id,
                'product_uom_qty': abs(mrp_production.product_qty),
                'product_uom': mrp_production.product_id.uom_id.id,
                'picking_id': picking.id,
                'location_id': location_id.id,
                'location_dest_id': location_dest_id.id,
                'group_id': group.id,
                'procure_method': 'make_to_order',
                'origin': self.name,
                'state': 'waiting',
                'date': mrp_production.date_finished,
            })

            finished_moves = mrp_production.move_finished_ids.filtered(
                lambda m: m.product_id == mrp_production.product_id
            )
            move_sale.move_orig_ids = [Command.link(fm.id) for fm in finished_moves]
        return picking
        
class PosOrderLine(models.Model):
    _inherit = "pos.order.line"
    
    mrp_production_ids = fields.One2many(
        'mrp.production',
        'pos_order_line_id',
        string='Manufacturing orders associated with this pos order line.')
