# -*- coding: utf-8 -*-
from odoo import api, fields, models, _ , Command


class PosOrder(models.Model):
    _inherit = 'pos.order'

    mrp_production_count = fields.Integer(
        "Count of MO generated",
        compute='_compute_mrp_production_ids',
        )
    
    mrp_production_ids = fields.Many2many(
        'mrp.production',
        string='Manufacturing orders associated with this pos order line.',
        compute="_compute_mrp_production_ids"
        )
    
    
    def _compute_mrp_production_ids(self):
        for rec in self:
            rec.mrp_production_ids = [Command.link(mrp.id) for mrp in rec.lines.mrp_production_ids]
            rec.mrp_production_count = len(rec.mrp_production_ids)

    
    def action_view_mrp_production(self):
        self.ensure_one()
        action = {
            'res_model': 'mrp.production',
            'type': 'ir.actions.act_window',
        }
        if len(self.mrp_production_ids) == 1:
            action.update({
                'view_mode': 'form',
                'res_id': self.mrp_production_ids.id,
            })
        else:
            action.update({
                'name': _("Manufacturing Orders Generated by %s", self.name),
                'domain': [('id', 'in', self.mrp_production_ids.ids)],
                'view_mode': 'list,form',
            })
        return action
    
    def create(self,vals_list):
        records = super().create(vals_list)
        for rec in records:
            for line in rec.lines:
                if line.product_id.product_tmpl_id.can_create_pos_mrp and line.qty > 0:
                    bom_id = self.env['mrp.bom'].search([
                        ('product_id', '=', line.product_id.id),
                    ],limit=1)
                    if not bom_id:
                        bom_id = self.env['mrp.bom'].search([
                            ('product_tmpl_id', '=', line.product_id.product_tmpl_id.id),
                            ('product_id', '=', False),
                        ],limit=1)
                        if not bom_id:
                            continue
                    
                    mrp_order = self.env['mrp.production'].create({
                        'origin': line.name,
                        'state': 'confirmed',
                        'product_tmpl_id': line.product_id.product_tmpl_id.id,
                        'product_id': line.product_id.id,
                        'product_uom_id': line.product_id.uom_id.id,
                        'product_qty': line.qty,
                        'bom_id': bom_id.id,
                        'product_description_variants': ','.join(line.attribute_value_ids.mapped('name')),
                        'pos_order_line_id': line.id
                    })
        
                    list_value = []
                    for bom_line in mrp_order.bom_id.bom_line_ids:
                        list_value.append((0, 0, {
                            'raw_material_production_id': mrp_order.id,
                            'name': mrp_order.name,
                            'product_id': bom_line.product_id.id,
                            'product_uom': bom_line.product_uom_id.id,
                            'product_uom_qty': (bom_line.product_qty * mrp_order.product_qty)/self.env['mrp.bom'].search([("product_tmpl_id", "=", line.product_id.product_tmpl_id.id)]).product_qty,
                            'picking_type_id': mrp_order.picking_type_id.id,
                            'location_id': mrp_order.location_src_id.id,
                            'location_dest_id': bom_line.product_id.with_company(self.company_id.id).property_stock_production.id,
                            'company_id': mrp_order.company_id.id,
                        }))
                    finished_vals = {
                        'product_id': line.product_id.id,
                        'product_uom_qty': line.qty,
                        'product_uom': line.product_id.uom_id.id,
                        'name': mrp_order.name,
                        'date_deadline': mrp_order.date_deadline,
                        'picking_type_id': mrp_order.picking_type_id.id,
                        'location_id': mrp_order.location_src_id.id,
                        'location_dest_id': mrp_order.location_dest_id.id,
                        'company_id': mrp_order.company_id.id,
                        'production_id': mrp_order.id,
                        'warehouse_id': mrp_order.location_dest_id.warehouse_id.id,
                        'origin': mrp_order.name,
                        'group_id': mrp_order.procurement_group_id.id,
                        'propagate_cancel': mrp_order.propagate_cancel,
                    }
                    mrp_order.update({
                        'move_raw_ids': list_value,
                        'move_finished_ids': [
                            (0, 0, finished_vals)]
                    })
        return records
    
class PosOrderLine(models.Model):
    _inherit = "pos.order.line"
    
    mrp_production_ids = fields.One2many(
        'mrp.production',
        'pos_order_line_id',
        string='Manufacturing orders associated with this pos order line.')
    